---

fabric_name: FABRIC

# Various fabric settings
fabric_type: l3ls-evpn
# Enable vlan aware bundles
evpn_vlan_aware_bundles: false

# core_interfaces:
#   p2p_links:
#     - nodes: [spine1, leaf1]
#       interfaces: [Ethernet3, Ethernet3]
#       ip: [10.10.1.1/30, 10.10.1.2/30]
#     - nodes: [spine1, leaf2]
#       interfaces: [Ethernet4, Ethernet3]
#       ip: [10.10.1.5/30, 10.10.1.6/30]
#     - nodes: [spine1, leaf3]
#       interfaces: [Ethernet5, Ethernet3]
#       ip: [10.10.1.9/30, 10.10.1.10/30]
#     - nodes: [spine1, leaf4]
#       interfaces: [Ethernet6, Ethernet3]
#       ip: [10.10.1.13/30, 10.10.1.14/30]

#     - nodes: [spine2, leaf1]
#       interfaces: [Ethernet3, Ethernet4]
#       ip: [10.10.2.1/30, 10.10.2.2/30]
#     - nodes: [spine2, leaf2]
#       interfaces: [Ethernet4, Ethernet4]
#       ip: [10.10.2.5/30, 10.10.2.6/30]
#     - nodes: [spine2, leaf3]
#       interfaces: [Ethernet5, Ethernet4]
#       ip: [10.10.2.9/30, 10.10.2.10/30]
#     - nodes: [spine2, leaf4]
#       interfaces: [Ethernet6, Ethernet4]
#       ip: [10.10.2.13/30, 10.10.2.14/30]

#     - nodes: [spine3, leaf1]
#       interfaces: [Ethernet3, Ethernet5]
#       ip: [10.10.3.1/30, 10.10.3.2/30]
#     - nodes: [spine3, leaf2]
#       interfaces: [Ethernet4, Ethernet5]
#       ip: [10.10.3.5/30, 10.10.3.6/30]
#     - nodes: [spine3, leaf3]
#       interfaces: [Ethernet5, Ethernet5]
#       ip: [10.10.3.9/30, 10.10.3.10/30]
#     - nodes: [spine3, leaf4]
#       interfaces: [Ethernet6, Ethernet5]
#       ip: [10.10.3.13/30, 10.10.3.14/30]


# Spine Switches
spine:
  defaults:
    platform: cEOS-lab
    bgp_as: 65100
    loopback_ipv4_pool: 172.16.0.0/24
    mlag: false
  nodes:
    - name: spine1
      id: 11
      mgmt_ip: 192.168.0.11/24
      # structured_config:
      #   loopback_interfaces:
      #     Loopback0:
      #       ip_address: 172.16.0.101/32
      #   interfaces:
      #     Ethernet3:
      #       description: P2P-to-Leaf1
      #       ip_address: 10.10.1.1/30
      #     Ethernet4:
      #       description: P2P-to-Leaf2
      #       ip_address: 10.10.1.5/30
      #     Ethernet5:
      #       description: P2P-to-Leaf3
      #       ip_address: 10.10.1.9/30
      #     Ethernet6:
      #       description: P2P-to-Leaf4
      #       ip_address: 10.10.1.13/30
      #   router_bgp:
      #     router_id: 172.16.0.101

    - name: spine2
      id: 12
      mgmt_ip: 192.168.0.12/24
      # structured_config:
      #   loopback_interfaces:
      #     Loopback0:
      #       ip_address: 172.16.0.102/32
      #   interfaces:
      #     Ethernet3:
      #       description: P2P-to-Leaf1
      #       ip_address: 10.10.2.1/30
      #     Ethernet4:
      #       description: P2P-to-Leaf2
      #       ip_address: 10.10.2.5/30
      #     Ethernet5:
      #       description: P2P-to-Leaf3
      #       ip_address: 10.10.2.9/30
      #     Ethernet6:
      #       description: P2P-to-Leaf4
      #       ip_address: 10.10.2.13/30
      #   router_bgp:
      #     router_id: 172.16.0.102

    - name: spine3
      id: 13
      mgmt_ip: 192.168.0.13/24
      # structured_config:
      #   loopback_interfaces:
      #     Loopback0:
      #       ip_address: 172.16.0.103/32
      #   interfaces:
      #     Ethernet3:
      #       description: P2P-to-Leaf1
      #       ip_address: 10.10.3.1/30
      #     Ethernet4:
      #       description: P2P-to-Leaf2
      #       ip_address: 10.10.3.5/30
      #     Ethernet5:
      #       description: P2P-to-Leaf3
      #       ip_address: 10.10.3.9/30
      #     Ethernet6:
      #       description: P2P-to-Leaf4
      #       ip_address: 10.10.3.13/30
      #   router_bgp:
      #     router_id: 172.16.0.103
    
    - name: spine4
      id: 14
      mgmt_ip: 192.168.0.14/24

# Leaf switches. Most leafs will be l3leaf, not l2leaf.
l3leaf:
  defaults:
    bgp_as: 65101-65105 # Gives a range which will be auto-assigned
    platform: cEOS-lab
    loopback_ipv4_pool: 172.16.0.0/28 # This is loopback0 (underlay)
    vtep_loopback_ipv4_pool: 172.16.1.0/28 # This is loopback1 (VTEP)
    uplink_interfaces: [Ethernet3, Ethernet4, Ethernet5, Ethernet6] # Leaf uplinks
    uplink_switches: [spine1, spine2, spine3, spine4] # Where the leaf uplinks go
    uplink_ipv4_pool: 10.10.1.0/24 # For the p2p interfaces to chopped up into /31s
    mlag_interfaces: [Ethernet1, Ethernet2] # MLAG peer link
    mlag_peer_ipv4_pool: 10.255.252.0/24 # MLAG peer IPs
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24 # iBGP peering between MLAG peers
    virtual_router_mac_address: 00:1c:73:00:00:99 # The vMAC for the anycast gateways
    spanning_tree_mode: mstp # Spanning Tree is still enabled even in EVPN setups
    spanning_tree_priority: 16384 
    mlag: true # By default, use MLAG
  node_groups: 
    - group: mlag1
      bgp_as: 65101 # bgp_as is configured automatically from the range, but can be overriden
      nodes:
        - name: leaf1
          id: 1
          mgmt_ip: 192.168.0.21/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3, Ethernet3, Ethernet3]
          # structured_config:
          #   loopback_interfaces:
          #     Loopback0:
          #       ip_address: 172.16.0.71/32
          #     Loopback1:
          #       ip_address: 172.16.1.71/32
          #   interfaces:
          #     Ethernet3:
          #       description: P2P-to-Spine1
          #       ip_address: 10.10.1.2/30
          #     Ethernet4:
          #       description: P2P-to-Spine2
          #       ip_address: 10.10.2.2/30
          #     Ethernet5:
          #       description: P2P-to-Spine3
          #       ip_address: 10.10.3.2/30
          #   router_bgp:
          #     router_id: 172.16.0.71
        - name: leaf2
          id: 2
          mgmt_ip: 192.168.0.22/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4, Ethernet4, Ethernet4]
          # structured_config:
          #   loopback_interfaces:
          #     Loopback0:
          #       ip_address: 172.16.0.72/32
          #     Loopback1:
          #       ip_address: 172.16.1.71/32
          #   interfaces:
          #     Ethernet3:
          #       description: P2P-to-Spine1
          #       ip_address: 10.10.1.6/30
          #     Ethernet4:
          #       description: P2P-to-Spine2
          #       ip_address: 10.10.2.6/30
          #     Ethernet5:
          #       description: P2P-to-Spine3
          #       ip_address: 10.10.3.6/30
          #   router_bgp:
          #     router_id: 172.16.0.72
    - group: mlag2
      bgp_as: 65103 # Overriden automatic allocation for host4/R1 peering
      nodes:
        - name: leaf3
          id: 3
          mgmt_ip: 192.168.0.23/24
          uplink_switch_interfaces: [Ethernet5, Ethernet5, Ethernet5, Ethernet5]
          # structured_config:
          #   loopback_interfaces:
          #     Loopback0:
          #       ip_address: 172.16.0.73/32
          #     Loopback1:
          #       ip_address: 172.16.1.73/32
          #   interfaces:
          #     Ethernet3:
          #       description: P2P-to-Spine1
          #       ip_address: 10.10.1.10/30
          #     Ethernet4:
          #       description: P2P-to-Spine2
          #       ip_address: 10.10.2.10/30
          #     Ethernet5:
          #       description: P2P-to-Spine3
          #       ip_address: 10.10.3.10/30
          #   router_bgp:
          #     router_id: 172.16.0.73
        - name: leaf4
          id: 4
          mgmt_ip: 192.168.0.24/24
          uplink_switch_interfaces: [Ethernet6, Ethernet6, Ethernet6, Ethernet6]
          # structured_config:
          #   loopback_interfaces:
          #     Loopback0:
          #       ip_address: 172.16.0.74/32
          #     Loopback1:
          #       ip_address: 172.16.1.73/32
          #   interfaces:
          #     Ethernet3:
          #       description: P2P-to-Spine1
          #       ip_address: 10.10.1.14/30
          #     Ethernet4:
          #       description: P2P-to-Spine2
          #       ip_address: 10.10.2.14/30
          #     Ethernet5:
          #       description: P2P-to-Spine3
          #       ip_address: 10.10.3.14/30
          #   router_bgp:
          #     router_id: 172.16.0.74



# There's an issue with vEOS with larger MTUs
p2p_uplinks_mtu: 1550

# BFD Settings
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3


# Needed for vEOS/cEOS

bgp_update_wait_install: false
bgp_update_wait_for_convergence: false

# Needed for Arista ATD Lab Environment
dns_domain: arista.lab
mgmt_interface: Management0
mgmt_interface_vrf: MGMT
mgmt_gateway: 192.168.0.1
